name: Keep Alive
on:
  schedule:
      - cron: '*/15 * * * *'
        rkflow_dispatch:
    jobs:
          :
              runs-on: ubuntu-latest
                  steps:
                        - name: Ping Streamlit App
                                run: curl -s -o /dev/null -w "%{http_code}" https://support-ticket-simulations.streamlit.app/
