name: Keep Alive
on:
  workflow_dispatch:
    schedule:
        - cron: '*/15 * * * *'
        jobs:
          ping:
              runs-on: ubuntu-latest
                  steps:
                        - run: curl https://support-ticket-simulations.streamlit.app/
                        
